### ISSUE TITLE
Support Symfony 4

### ISSUE THREAD

**Issue by ThomasTr** [AntoineTesson/QRcodeBundle#1]
Hi,

would it be possible to bump the dependencies to support symfony 4?

Thx and merry christmas :)

**Comment by AntoineTesson** [comment]
Hi, 

I have bumped on symfony 4 on the dependencies file.
Warning, i'm on holidays , i can't test this modification !

So i'm not sure if the bundle work's fine on symfony 4.
U can dl this bundle on the dev-master version for test on symfony 4

Happy new year

**Comment by ThomasTr** [comment]
Hi,

thank you for your  support in your holidays. Installation went fine. I'm currently in the migration phase to symfony 4 and have a long walk to get all dependencies and errors fixed. So i can't currently say if your bundle work finally under symfony 4, but will give you feedback, when I'm at this point.

Also happy new year 👍

**Comment by AntoineTesson** [comment]
Ok ! thank's you

**Comment by AntoineTesson** [comment]
Hello any news for this bundler under SF4 ?

**Comment by luiscmas** [comment]
Hi @AntoineTesson, I'm going to test it these days. 
I did a 
php composer.phar require yellowskies/QR-code-bundle:dev-master

**Comment by luiscmas** [comment]
For me is working fine in SF4!!

**Comment by AntoineTesson** [comment]
Nice i'll go to create 1.5 branch for SF4 ( to not have to use the dev:master)
