### ISSUE TITLE
Symfony 5.4 Deprecation Warning

### ISSUE THREAD

**Issue by Chris53897** [AntoineTesson/QRcodeBundle#11]
I am not sure if there are more depcreations right now.
Should be fixed for Support for Symfony 6.x

`Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Skies\QRcodeBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by AntoineTesson** [comment]
Thank's ! i have merged your code i will report this in a new version not only in the master version

**Comment by AntoineTesson** [comment]
I don't use SF6 yet, only 5.4. I will check this next days, but if u confirm before my tests with pleasure !

**Comment by Chris53897** [comment]
I did not check if it works with symfony 6. I can maybe check it tomorrow.
The deprecation messages just popped up after every request.
