### ISSUE TITLE
Barcode in not working

### ISSUE THREAD

**Issue by KotetsuNoAkai** [AntoineTesson/QRcodeBundle#2]
Hi:

I have a proyect hosted in AWS and barcode is no generating a QR. This is the code:
```

 {%  set qr = barcode({code: url('dataCard',{'card':card.url}), type: 'qrcode', format: 'png', color: [0, 0, 0]})  %}
    <div class="codigo-qr"> <img src="{{ 'data:image/png;base64,' ~ qr }}" /></div>
```

In my local machine, is working Ok and generating the image.

**Comment by KotetsuNoAkai** [comment]
Solved:

This plugin needs the extension : GD.

Install and it works

**Comment by AntoineTesson** [comment]
Hello ! 

If there is some problem of requirements, make sure you have install these two extensions of PHP (check in your phpinfo()).

    Barcodes requires GD and ImageMagick to create PNGs in PHP 5.3.
    Barcodes requires PHP bcmath extension for Intelligent Mail barcodes


Have a good day ! =)
