### ISSUE TITLE
Composer update to Symfony 4.4 - PHP Fatal error:  Class 'Twig_Extension' not found in vendor/yellowskies/qr-code-bundle/Twig/Extensions/Barcode.php on line 14

### ISSUE THREAD

**Issue by ingcarlosperez** [AntoineTesson/QRcodeBundle#6]
Hi your work is great, is very useful.

I tried to upgrade a Symfony project from version 4.3 to 4.4 and I got this error:

PHP Fatal error:  Class 'Twig_Extension' not found in /home/carlos/www/gdocumentBack_sf44/vendor/yellowskies/qr-code-bundle/Twig/Extensions/Barcode.php on line 14
Symfony\Component\Debug\Exception\ClassNotFoundException^ {#7689
  #message: """
    Attempted to load class "Twig_Extension" from the global namespace.\n
    Did you forget a "use" statement?
    """
  #code: 0
  #file: "./vendor/yellowskies/qr-code-bundle/Twig/Extensions/Barcode.php"
  #line: 14
  #severity: E_ERROR
}

Thanks for your help.

**Comment by AntoineTesson** [comment]
Hello , have u can try to add "twig/extensions", "*" to the composer.json require section

**Comment by ingcarlosperez** [comment]
Hi,  I added "twig/extensions": "*" in composer.json and this change worked for me. My project upgraded to Symfony 4.4.1 correctly. I tested the barcode and QR generation and the request executed it without problems.

Thanks for your help!
